framework:
    secret: '%env(APP_SECRET)%'
    annotations: true 
    http_method_override: false
    handle_all_throwables: true

    session:
        handler_id: null
        cookie_secure: auto  # Ensure HTTPS if required
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native  # Make sure sessions are correctly stored
        # Uncomment below for a custom session handler if needed
        # handler_id: 'session.handler.native_file'
        # save_path: '%kernel.cache_dir%/sessions' # Optional: Custom save path for session files

    router:
        default_uri: 'http://localhost:8000'

    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
